#!/usr/bin/env bash

# Load Yabai scripting addition.
sudo yabai --load-sa
yabai -m signal --add event="dock_did_restart" action="sudo yabai --load-sa"

# Layout settings.
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config auto_balance off
yabai -m config split_ratio 0.5

yabai -m config --space 1 layout float

# Gaps settings.
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

# Status bar gaps settings.
# TODO: yabai -m config external_bar all:0:0

# Window modifications.
yabai -m config window_shadow float

yabai -m config window_opacity on
yabai -m config active_window_opacity 0.99
yabai -m config normal_window_opacity 0.95

# Mouse settings.
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus on

# Godot-specific settings.
yabai -m rule --add app="Godot" manage=off
yabai -m rule --add app="Godot" title=".+ - Godot Engine" manage=on
